name: Python CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: if: "contains(github.event_name, 'push') && (contains(github.event.head_commit.modified, '.py') || contains(github.event.head_commit.added, '.py')"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4   

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pip-tools
        run: python -m pip install pip-tools

      - name: Generate requirements.txt
        run: pip-compile --output-file requirements.txt requirements.in

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest test/
          coverage report -m

      - name: Check code formatting
        run: black --check .

      - name: Check for added files
        run: git diff --name-only --diff-filter=d HEAD^

      - name: Lint with flake8
        run: pip install flake8 && flake8
